In [3]:
import pandas as pd

In [4]:
btc=pd.read_csv("BTC_USD_2021-02-27_2021-05-26-CoinDesk.csv")
btc

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,BTC,2021-02-27,46642.606077,46326.824066,48353.001000,46207.705779
1,BTC,2021-02-28,45092.806573,46204.058564,46675.197850,43119.157024
2,BTC,2021-03-01,49248.914013,45234.368757,49520.724994,45044.383764
3,BTC,2021-03-02,47900.776878,49636.021465,50211.437170,47200.042169
4,BTC,2021-03-03,50811.855174,48526.990362,52636.222988,48195.123104
...,...,...,...,...,...,...
84,BTC,2021-05-22,37490.941888,37359.782014,38889.859694,35304.227598
85,BTC,2021-05-23,34259.548416,37521.890770,38267.299279,31179.690362
86,BTC,2021-05-24,38085.789361,34737.628018,39966.876470,34485.431042
87,BTC,2021-05-25,38290.448528,38888.319531,39855.116340,36498.639529
88,BTC,2021-05-26,38915.004829,38381.736022,40894.436768,37857.499785

In [7]:
eth=pd.read_csv("ETH_USD_2021-02-27_2021-05-26-CoinDesk.csv")
eth

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,ETH,2021-02-27,1495.812837,1445.351151,1527.546356,1439.936061
1,ETH,2021-02-28,1412.713189,1461.107237,1470.862514,1303.330506
2,ETH,2021-03-01,1555.844780,1421.729861,1565.393172,1412.935231
3,ETH,2021-03-02,1483.912043,1571.082365,1603.538083,1458.207951
4,ETH,2021-03-03,1593.878998,1489.516097,1653.203488,1478.791037
...,...,...,...,...,...,...
84,ETH,2021-05-22,2329.034728,2436.728085,2489.233274,2159.563417
85,ETH,2021-05-23,2080.371420,2298.970751,2383.759830,1733.578541
86,ETH,2021-05-24,2539.997864,2099.628025,2678.139772,2088.219083
87,ETH,2021-05-25,2691.537214,2653.064289,2754.075156,2387.126617
88,ETH,2021-05-26,2821.622828,2707.736887,2914.889877,2651.466474

In [10]:
USDT=pd.read_csv("USDT_USD_2021-02-27_2021-05-26-CoinDesk.csv")
USDT

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,USDT,2021-02-27,1.001411,1.000229,1.002015,0.999627
1,USDT,2021-02-28,1.002423,1.002014,1.003149,1.000235
2,USDT,2021-03-01,1.000705,1.001760,1.003763,1.000542
3,USDT,2021-03-02,1.001275,1.000522,1.002091,1.000064
4,USDT,2021-03-03,1.000610,1.001589,1.001726,1.000085
...,...,...,...,...,...,...
84,USDT,2021-05-22,1.001770,1.002243,1.002748,1.001336
85,USDT,2021-05-23,1.001980,1.001611,1.003026,1.000855
86,USDT,2021-05-24,1.002322,1.001856,1.002923,1.001336
87,USDT,2021-05-25,1.001200,1.002073,1.002973,1.000903
88,USDT,2021-05-26,1.001573,1.001260,1.002404,1.000769

In [12]:
frame=btc.append([eth,USDT])
frame

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,BTC,2021-02-27,46642.606077,46326.824066,48353.001000,46207.705779
1,BTC,2021-02-28,45092.806573,46204.058564,46675.197850,43119.157024
2,BTC,2021-03-01,49248.914013,45234.368757,49520.724994,45044.383764
3,BTC,2021-03-02,47900.776878,49636.021465,50211.437170,47200.042169
4,BTC,2021-03-03,50811.855174,48526.990362,52636.222988,48195.123104
...,...,...,...,...,...,...
84,USDT,2021-05-22,1.001770,1.002243,1.002748,1.001336
85,USDT,2021-05-23,1.001980,1.001611,1.003026,1.000855
86,USDT,2021-05-24,1.002322,1.001856,1.002923,1.001336
87,USDT,2021-05-25,1.001200,1.002073,1.002973,1.000903
88,USDT,2021-05-26,1.001573,1.001260,1.002404,1.000769

In [24]:
doge=pd.read_csv("DOGE-USD (1).csv")
doge["Currency"]="DOGE"
dogeCurrency=doge[['Currency','Date','Close','Open','High','Low']]
dogeCurrency.columns=['Currency','Date','Closing Price (USD)','24h Open (USD)','24h High (USD)','24h Low (USD)']
dogeCurrency

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,DOGE,2020-03-01,0.002275,0.002233,0.002297,0.002223
1,DOGE,2020-03-02,0.002349,0.002278,0.002370,0.002256
2,DOGE,2020-03-03,0.002499,0.002348,0.002525,0.002316
3,DOGE,2020-03-04,0.002398,0.002500,0.002508,0.002367
4,DOGE,2020-03-05,0.002506,0.002399,0.002531,0.002395
...,...,...,...,...,...,...
448,DOGE,2021-05-23,0.308071,0.342522,0.350863,0.249437
449,DOGE,2021-05-24,0.366162,0.306715,0.371485,0.296291
450,DOGE,2021-05-25,0.346302,0.366041,0.380010,0.323497
451,DOGE,2021-05-26,0.353693,0.346396,0.365920,0.338857
452,DOGE,2021-05-27,0.333750,0.351704,0.351704,0.328144

In [39]:
framefinal=frame.append(dogeCurrency)
final=framefinal.reset_index()
final_df=final.drop('index', axis=1)
final_df

,Currency,Date,Closing Price (USD),24h Open (USD),24h High (USD),24h Low (USD)
0,BTC,2021-02-27,46642.606077,46326.824066,48353.001000,46207.705779
1,BTC,2021-02-28,45092.806573,46204.058564,46675.197850,43119.157024
2,BTC,2021-03-01,49248.914013,45234.368757,49520.724994,45044.383764
3,BTC,2021-03-02,47900.776878,49636.021465,50211.437170,47200.042169
4,BTC,2021-03-03,50811.855174,48526.990362,52636.222988,48195.123104
...,...,...,...,...,...,...
715,DOGE,2021-05-23,0.308071,0.342522,0.350863,0.249437
716,DOGE,2021-05-24,0.366162,0.306715,0.371485,0.296291
717,DOGE,2021-05-25,0.346302,0.366041,0.380010,0.323497
718,DOGE,2021-05-26,0.353693,0.346396,0.365920,0.338857
719,DOGE,2021-05-27,0.333750,0.351704,0.351704,0.328144

In [40]:
final_df.to_csv('historical.csv', index=False)